version: 2.1 
jobs:
  build: 
    docker: 
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "hello general assembly" 
  test: 
    docker: 
      - image: circleci/ruby:2.4-node
    steps: 
      - checkout
      - run: echo "testing your code"

    
# workflows iniated for simple demo of parallel runs 