version: 2.1 
orbs:
  hello-build: circleci/hello-build@0.0.14

jobs:
  build: 
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "building your code" 
  
  test_a: 
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test --test/test.js
      - store_test_results:
          path: test
      - store_artifacts:
          path: test  

  approval:     
    docker: 
      - image: circleci/node:latest
    steps: 
      - run: echo "please approve this job"

  deploy:     
    docker: 
      - image: circleci/node:latest
    steps: 
      - run: echo "deploying"

workflows: 
  version: 2.1
  hello_world: 
    jobs: 
      - hello-build/hello-build
  build_test_deploy: 
    jobs: 
      - build
      - test_a: 
          requires: 
            - build
      - approval:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
            - test_a 

      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
            - test_a
            - approval

