version: 2.1 
# here we are going to set what we want to run - we call this 'jobs'
jobs:
  # first job we have is a build job where we will checkout the code then run a shell command
  build: 
    docker: 
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "building your code" 
  # second job we have is a test job where we will also run a shell command
  test: 
    docker: 
      - image: circleci/ruby:2.4-node
    steps: 
      - checkout
      - run: echo "testing your code"
  # third job we're deploying our code to production!    
  deploy: 
    docker: 
      - image: circleci/ruby:2.4-node
    steps: 
      - run: echo "deploying your code"
# to have these jobs work together we iniiate a 'workflow' where we call upon the jobs defined above
workflows: 
  version: 2.1
  build_and_test: 
    jobs: 
      - build
      # let's make sure that test only runs if build passes
      - test: 
          requires: 
            - build
      - deploy: 
          requires: 
            - test
          
         