version: 2.1 
orbs:
  hello-build: circleci/hello-build@0.0.14

jobs:
  build: 
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "building your code" 
  
  test_a: 
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: mkdir ~/junit
      - run:
          command: mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit  
   
  approval:     
    docker: 
      - image: circleci/node:latest
    steps: 
      - run: echo "please approve this job"

  deploy:     
    docker: 
      - image: circleci/node:latest
    steps: 
      - run: echo "Deploying to Surge"

workflows: 
  version: 2.1
  hello_world: 
    jobs: 
      - hello-build/hello-build
  build_test_deploy: 
    jobs: 
      - build
      - test_a: 
          requires: 
            - build
      - approval:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - test_a 

      - deploy:
          filters:
            branches:
              only: master
          requires:
            - approval

