version: 2.1 
orbs:
  hello-build: circleci/hello-build@0.0.14

jobs:
  build: 
    docker: 
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "building your code" 
  
  test_a: 
    docker: 
      - image: circleci/ruby:2.4-node
    parallelism: 3
    steps: 
      - checkout
      - run: echo "this is test a"
  test_b:
    docker: 
      - image: circleci/ruby:2.4-node
    parallelism: 2
    steps: 
      - checkout
      - run: echo "this is test b"
   
  deploy:     
    docker: 
      - image: circleci/ruby:2.4-node
    steps: 
      - run: echo "deploying your code"

workflows: 
  version: 2.1
  hello_world: 
    jobs: 
      - hello-build/hello-build
  build_test_deploy: 
    jobs: 
      - build

      - test_a: 
          requires: 
            - build
      - test_b: 
          requires:
            - build

      - deploy:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - test_a 
            - test_b          
